"""added new columns v5

Revision ID: 4f01177a4918
Revises: c21fca354d8e
Create Date: 2025-02-16 18:57:08.301345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f01177a4918'
down_revision = 'c21fca354d8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cgst', sa.Numeric(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('firm', schema=None) as batch_op:
        batch_op.drop_column('cgst')

    # ### end Alembic commands ###
