"""added new columns

Revision ID: a6e48e9e654a
Revises: 
Create Date: 2025-01-04 14:10:46.440518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e48e9e654a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firm',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('short_description', sa.String(length=80), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('address_line1', sa.String(length=35), nullable=True),
    sa.Column('address_line2', sa.String(length=35), nullable=True),
    sa.Column('address_line3', sa.String(length=35), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('gstin_number', sa.String(length=35), nullable=True),
    sa.Column('logo_image_path', sa.String(length=1024), nullable=True),
    sa.Column('invoice_template', sa.LargeBinary(), nullable=False),
    sa.Column('account_name', sa.String(length=120), nullable=True),
    sa.Column('account_number', sa.String(length=100), nullable=True),
    sa.Column('ifsc_code', sa.String(length=100), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('branch_name', sa.String(length=100), nullable=True),
    sa.Column('thank_message', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('firm')
    # ### end Alembic commands ###
